version: '3.9'

services:
  web:
    build: .
    hostname: oncall
    container_name: oncall-web
    ports:
      - 8081:8080
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
  
  mysql:
    image: mysql:5.7
    container_name: oncall-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - iris

  blackbox:
    image: prom/blackbox-exporter:v0.12.0
    container_name: blackbox
    ports:
    - 9115:9115
    command:
    - --config.file=/etc/blackbox/blackbox.yml
    volumes:
    - ./configs/blackbox.yml:/etc/blackbox/blackbox.yml
    depends_on:
    - web
    networks:
      - iris
networks:
  iris:
    name: iris

volumes:
    prometheus_data: {}