modules: 
  http_2xx:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: "ipv4"
  tcp_connect:
    prober: tcp
    timeout: 15s
    tcp:
      preferred_ip_protocol: "ipv4"
  icmp:
    prober: icmp
    timeout: 15s
    icmp:
      preferred_ip_protocol: "ipv4"
  dns_udp:
    prober: dns
    timeout: 15s