global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - '/etc/prometheus/rules.yml'

scrape_configs:
  - job_name: "oncall"
    static_configs:
      - targets: ["oncall:8082"]

  - job_name: "oncall-duties"
    static_configs:
      - targets: ["duties-exporter:8090"]

  - job_name: "oncall-mysql"
    metrics_path: /metrics
    static_configs:
      - targets: ["prom-mysql-exporter:9104"]

  - job_name: blackbox
    metrics_path: /metrics
    static_configs:
      - targets:
        - blackbox:9115

  - job_name: blackbox-oncall-http # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [oncall:8080]
    static_configs:
      - targets:
        - blackbox:9115

  - job_name: blackbox-oncall-healthcheck # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [oncall:8080/healthcheck]
    static_configs:
      - targets:
        - blackbox:9115

  - job_name: blackbox-oncall-tcp # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [tcp_connect]
      target: [oncall:8080]
    static_configs:
      - targets:
        - blackbox:9115

  - job_name: blackbox-mysql-tcp # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [tcp_connect]
      target: [mysql:3306]
    static_configs:
      - targets:
        - blackbox:9115

  - job_name: blackbox-oncall-metrics-tcp # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [tcp_connect]
      target: [oncall:8082]
    static_configs:
      - targets:
        - blackbox:9115

  - job_name: blackbox-oncall-icmp # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [icmp]
      target: [oncall]
    static_configs:
      - targets:
        - blackbox:9115

  - job_name: blackbox-google-dns # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [dns_udp]
      target: [8.8.8.8:53]
    static_configs:
      - targets:
        - blackbox:9115 

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets:
        - cadvisor:8080

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093